[package]
name = "asset-pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used by ructe for image mime type detection
mime = "0.3.0"