[package]
name = "ui-components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { version = "0.1.0", path = "../db" }
dioxus = { version = "0.2", features = ["ssr"] }
